[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19"
reqwasm = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
